### ISSUE TITLE
SSL problems: setup server, cannot connect to 8443

### ISSUE THREAD

**Issue by Apprisco** [Alovoa/alovoa#125]
Hello!
I fully setup the (customized) backend to my server, and realized that I cannot actually access port 8443 as it isn't using SSL right now.
Do I have to use port 443 for now? And use a SSL certificate later?

![image](https://user-images.githubusercontent.com/34324909/148536287-3c38a625-5f71-4000-9b6d-413a545fc6ee.png)
Using port 443 did not work, I have absolutely no idea how I'd go about fixing this.
java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x020x000x010x000x010xfc0x030x030xe2N0xb6>0x8bq0xf30xfc0xe60xfa0xe5Q0xb5O0xfaJ0x860xc8"0xcf80x150xa90xb2tJ0xe1/0xbf0xcaBL ]. HTTP method names must be tokens
at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:419)
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:269)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1722)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Apprisco** [comment]
![image](https://user-images.githubusercontent.com/34324909/148536287-3c38a625-5f71-4000-9b6d-413a545fc6ee.png)
Using port 443 did not work, I have absolutely no idea how I'd go about fixing this.

**Comment by Apprisco** [comment]
java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x020x000x010x000x010xfc0x030x030xe2N0xb6>0x8bq0xf30xfc0xe60xfa0xe5Q0xb5O0xfaJ0x860xc8"0xcf80x150xa90xb2tJ0xe1/0xbf0xcaBL ]. HTTP method names must be tokens
        at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:419)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:269)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1722)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Apprisco** [comment]
Running into even more issues now without changes... sigh.

**Comment by Nonononoki** [comment]
Remove this line from SecurityConfig: 
`http.requiresChannel().anyRequest().requiresSecure();`

**Comment by Apprisco** [comment]
I cannot believe I didn't see that... I even went as far as to add a line in securityConfig to allow non-secure, but missed that line. Maybe I should get some sleep, thank you so much. Other issues stil lremain however... unsupportedaudioexception is weird.
