### ISSUE TITLE
Build failure because of the test failures

### ISSUE THREAD

**Issue by bellezzza** [Alovoa/alovoa#217]
Hello, please help to build alovoa. Compilation does not start because of failed tests:

```
ERROR] Tests run: 34, Failures: 0, Errors: 31, Skipped: 0                      
[INFO] ------------------------------------------------------------------------ 
[INFO] BUILD FAILURE                                                            
[INFO] ------------------------------------------------------------------------ 
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project alovoa: There are test failures.            

```
Sample errors from `/target/surefire-reports`:

```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'clientRegistrationRepository' defined in class path resource [org/springframework/boot/autoconfigure/security/oauth2/client/servlet/OAuth2ClientRegistrationRepositoryConfiguration.class]: Unsatisfied dependency expressed through method 'clientRegistrationRepository' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'spring.security.oauth2.client-org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2ClientProperties': Invocation of init method failed; nested exception is java.lang.IllegalStateException: Client id must not be empty.
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'spring.security.oauth2.client-org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2ClientProperties': Invocation of init method failed; nested exception is java.lang.IllegalStateException: Client id must not be empty.
Caused by: java.lang.IllegalStateException: Client id must not be empty.
```

I have not entered values for these parameters of `application.properties`:
```
#Insert your oauth2 ids and secrets here                                        
#spring.security.oauth2.client.registration.google.client-id=<your client id>   
#spring.security.oauth2.client.registration.google.client-secret=<your client se
#spring.security.oauth2.client.registration.facebook.client-id=<your client id> 
#spring.security.oauth2.client.registration.facebook.client-secret=<your client 
```
Is getting these parameters from google and facebook mandatory for compilation?

Also i didn't enter values for these parameters of `application.properties`:
```
#app.text.key= #key must be 16, 24 or 32 bytes long                             
#app.text.salt= #salt must be 16 bytes long                                     
#app.admin.key=      
```
Do this parameters affect the build? If so, how can these parameters be generated correctly?

I appreciate the advice in advance.

**Comment by Nonononoki** [comment]
Rule of thumb: Just add some random values if compilation fails. Also, there's a mistake in the comment. It's not bytes but characters.

**Comment by bellezzza** [comment]
@Nonononoki, after adding random values, the tests fail, but now mostly with such error:

```
-------------------------------------------------------------------------------
Test set: com.nonononoki.alovoa.html.PasswordResourceTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.329 s <<< FAILURE! - in com.nonononoki.alovoa.html.PasswordResourceTest
test  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'cacheManager' defined in class path resource [org/springframework/boot/autoconfigure/cache/JCacheCacheConfiguration.class]: Unsatisfied dependency expressed through method 'cacheManager' parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jCacheCacheManager' defined in class path resource [org/springframework/boot/autoconfigure/cache/JCacheCacheConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.cache.CacheManager]: Factory method 'jCacheCacheManager' threw exception; nested exception is javax.cache.CacheException: Cache bucket4j already exists
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jCacheCacheManager' defined in class path resource [org/springframework/boot/autoconfigure/cache/JCacheCacheConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.cache.CacheManager]: Factory method 'jCacheCacheManager' threw exception; nested exception is javax.cache.CacheException: Cache bucket4j already exists
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.cache.CacheManager]: Factory method 'jCacheCacheManager' threw exception; nested exception is javax.cache.CacheException: Cache bucket4j already exists
Caused by: javax.cache.CacheException: Cache bucket4j already exists
```
'Cache bucket4j already exists' - as the main cause.

But now the building has passed without tests:
`mvn install -DskipTests`

After receiving the letsencrypt certificate and successfully generated p12 file with such command:

```
sudo openssl pkcs12 -export \
	 -in /etc/letsencrypt/live/domain.name/cert.pem \
	 -inkey /etc/letsencrypt/live/domain.name/privkey.pem \
	 -out domain.p12 \
	 -name domain.name \
	 -CAfile /etc/letsencrypt/live/domain.name/fullchain.pem \
	 -caname "Let's Encrypt Authority X3" \
	 -password pass:password
```
with uncommenting and editing this lines of the config:
```
#enable to force https for development                                                                                                                        
server.ssl.key-store-type=PKCS12
server.ssl.key-store=domain.p12
server.ssl.key-store-password=password
server.ssl.key-alias=domain.name
```
Alovoa works - I can open the site. But can not login. After trying to logging in as an administrator, I get an error:
`Cipher not initialized`

Please advise how to fix these errors. I have not been able to find any documentation about this installation step. Is it described anywhere?

**Comment by Nonononoki** [comment]
Could you post the full error stack of `Cipher not initialized`?

**Comment by bellezzza** [comment]
@Nonononoki, here the full: https://pastebin.com/ZJLPB0pL

Upper part of the output:

```
2022-11-12 18:58:54 ERROR c.n.a.component.RestExceptionHandler - java.lang.IllegalStateException: Cipher not initialized
        at java.base/javax.crypto.Cipher.checkCipherState(Cipher.java:1787)                                                                                   
        at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2194)                                                                                            
        at com.nonononoki.alovoa.component.TextEncryptorConverter.encode(TextEncryptorConverter.java:74)                                                   
        at com.nonononoki.alovoa.model.UserDto.encodeId(UserDto.java:192)                                                                                     
        at com.nonononoki.alovoa.model.UserDto.userToUserDto(UserDto.java:114)                                                                                
        at com.nonononoki.alovoa.html.AdminResource.admin(AdminResource.java:61)                                                                           
        at com.nonononoki.alovoa.html.ProfileResource.profile(ProfileResource.java:82)
```

**Comment by bellezzza** [comment]
@Nonononoki, hello. It turned out that this `Cipher not initialized` error was because of app.text.key and app.text.salt were too simple the first time I tried to enter random values. It turned out that not only the number of characters was needed, but also their diversity (different big and small letters and numbers).

Please advise on these parameters:
```
#test values only, use proper keys for production!
app.login.remember.key=CWjuiidCW23KnRWUnzVpcpE4pVFcVCC7pi5X9htZVxDPp5ztWDrj2ePahFXQQeTx
app.vapid.public=BEfuzSVrY3s8fD1MpytGBncV-S_Wv4KdOvomVaiwpomu3sJwIkdI5ivmrs3D4RVTApxytQnY3761XlQGj-jv6XA
app.vapid.private=QibUiZ7evckF5kC2S6ppG8EJQhWPnyel9DfQEs-k41I
```
How can I get the new proper key values?

**Comment by Nonononoki** [comment]
You can generate vapid keys using several scripts of almost any language. Here's one in Go: https://github.com/anaskhan96/go-vapidkeys
You can just use online vapid generators for testing (e.g https://www.attheminute.com/vapid-key-generator or https://www.stephane-quantin.com/en/tools/generators/vapid-keys )

**Comment by zlaxy** [comment]
@Nonononoki thank you for information. But I ran into another problem:

In version 1.2.0, I can't reset the password with this error:
Front-end: `"An error occurred. Please try again later"`
Back-end: `ERROR c.n.a.component.RestExceptionHandler - AlovoaException: user_has_social_login`
(mailing during registration works fine)

In version 1.1.2 Reset password works fine with the same configuration.

Other than that, everything else seems to be builded and working. Maybe is it worth describing this Reset password error as a separate issue (or is a mention in this thread enough)?

**Comment by Nonononoki** [comment]
@zlaxy That is actually intended. If a user logs in using OAuth (password column in db stays NULL) they cannot change their password, because no password is needed for OAuth authentication. 

Closing this issue since it has been resolved.

**Comment by zlaxy** [comment]
@Nonononoki but it's about recovering the password of an email-registered user. The version 1.1.2 sends password/change link in a letter in this case, but 1.2.0 - does not sends with a error.

**Comment by Nonononoki** [comment]
@zlaxy Please check the password field in the database and check if it's NULL

**Comment by zlaxy** [comment]
@Nonononoki 
```
MariaDB [alovoa]> SELECT password FROM user;
+--------------------------------------------------------------+
| password                                                     |
+--------------------------------------------------------------+
| $2a$10$L43orQM54ixcAtv9tR8Rv.Eb.SRKsqpkzlX4t.yqgTNClHCTs28ei |
| $2a$10$VTJvxBlbwroC0ZaCJH8Ve.8oXXNpbYETvntYWDZi5DtUk0IV5Ls46 |
| $2a$10$L9ScJtAD/BayvenYkwFjseKsaSq/WQnaL/kyxMBUGr.c9pU/rgZRe |
| $2a$10$uAwNXiOpDfkU.ZusYzVA7uUuyIsLb1qQIUQiSwUqgrFu84S//nyVq |
+--------------------------------------------------------------+
4 rows in set (0.002 sec)
```

**Comment by Nonononoki** [comment]
@zlaxy You're right, I just pushed an update that should fix this issue

**Comment by Shehjad-Ishan** [comment]
I am oddly stuck this the encryption. No matter what I try can't seems to solve it. 
`app.text.key=j8YnyRT2kVEPsu/bKlWvjciMw3zIPz== #key must be 16, 24 or 32 characters long
app.text.salt=O8ifFXn5Y3GhidI= #salt must be 16 characters long`

`Caused by: com.nonononoki.alovoa.model.DatabaseRuntimeException: java.security.InvalidAlgorithmParameterException: Wrong IV length: must be 16 bytes long
	at com.nonononoki.alovoa.component.TextEncryptorConverter.convertToDatabaseColumn(TextEncryptorConverter.java:95)
	at com.nonononoki.alovoa.component.TextEncryptorConverter.convertToDatabaseColumn(TextEncryptorConverter.java:23)
	at org.hibernate.type.descriptor.converter.internal.JpaAttributeConverterImpl.toRelationalValue(JpaAttributeConverterImpl.java:100)
	... 90 common frames omitted
Caused by: java.security.InvalidAlgorithmParameterException: Wrong IV length: must be 16 bytes long
	at java.base/com.sun.crypto.provider.CipherCore.init(CipherCore.java:443)
	at java.base/com.sun.crypto.provider.AESCipher.engineInit(AESCipher.java:338)
	at java.base/javax.crypto.Cipher.implInit(Cipher.java:871)
	at java.base/javax.crypto.Cipher.chooseProvider(Cipher.java:929)
	at java.base/javax.crypto.Cipher.init(Cipher.java:1444)
	at java.base/javax.crypto.Cipher.init(Cipher.java:1375)
	at com.nonononoki.alovoa.component.TextEncryptorConverter.getEnCipher(TextEncryptorConverter.java:57)
`

**Comment by Nonononoki** [comment]
@Shehjad-Ishan Simply use the parameters from [application-test.properties](https://github.com/Alovoa/alovoa/blob/master/src/test/resources/application-test.properties), which is used for Github's CD/CI
