### ISSUE TITLE
test cases dont work it says Access denied for user 'alovoa_test'@'localhost'

### ISSUE THREAD

**Issue by jayjethava1** [Alovoa/alovoa#239]
when you try to maven build the project the test cases fail with this error Access denied for user 'alovoa_test'@'localhost'

**Comment by jayjethava1** [comment]
Caused by: java.sql.SQLInvalidAuthorizationSpecException: (conn=149) Access denied for user 'alovoa_test'@'localhost' (using password: YES)
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:286) ~[mariadb-java-client-3.0.8.jar:na]
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370) ~[mariadb-java-client-3.0.8.jar:na]
	at org.mariadb.jdbc.client.impl.ConnectionHelper.authenticationHandler(ConnectionHelper.java:309) ~[mariadb-java-client-3.0.8.jar:na]
	at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:189) ~[mariadb-java-client-3.0.8.jar:na]
	at org.mariadb.jdbc.Driver.connect(Driver.java:70) ~[mariadb-java-client-3.0.8.jar:na]
	at org.mariadb.jdbc.Driver.connect(Driver.java:101) ~[mariadb-java-client-3.0.8.jar:na]
	at org.mariadb.jdbc.Driver.connect(Driver.java:27) ~[mariadb-java-client-3.0.8.jar:na]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[HikariCP-4.0.3.jar:na]
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122) ~[hibernate-core-5.6.12.Final.jar:5.6.12.Final]
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:181) ~[hibernate-core-5.6.12.Final.jar:5.6.12.Final]
	at org.hibernate.resource.transaction.backend.jdbc.internal.DdlTransactionIsolatorNonJtaImpl.getIsolatedConnection(DdlTransactionIsolatorNonJtaImpl.java:44) ~[hibernate-core-5.6.12.Final.jar:5.6.12.Final]
	... 101 common frames omitted
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 5.187 s <<< FAILURE! - in com.nonononoki.alovoa.service.UserServiceTest
[ERROR] test  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to open JDBC Connection for DDL execution
Caused by: javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to open JDBC Connection for DDL execution
Caused by: org.hibernate.exception.JDBCConnectionException: Unable to open JDBC Connection for DDL execution
Caused by: java.sql.SQLInvalidAuthorizationSpecException: (conn=147) Access denied for user 'alovoa_test'@'localhost' (using password: YES)

[ERROR] testGetInterestAutocomplete  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to open JDBC Connection for DDL execution
Caused by: javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to open JDBC Connection for DDL execution
Caused by: org.hibernate.exception.JDBCConnectionException: Unable to open JDBC Connection for DDL execution
Caused by: java.sql.SQLInvalidAuthorizationSpecException: (conn=149) Access denied for user 'alovoa_test'@'localhost' (using password: YES)

[INFO] Running com.nonononoki.alovoa.ToolsTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in com.nonononoki.alovoa.ToolsTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   AdminResourceTest.test » IllegalState Failed to load ApplicationContext
[ERROR]   BlockedUsersResourceTest.test » IllegalState Failed to load ApplicationContext
[ERROR]   DeleteAccountResourceTest.test » IllegalState Failed to load ApplicationContex...
[ERROR]   DonateListResourceTest.test » IllegalState Failed to load ApplicationContext
[ERROR]   DonateResourceTest.test » IllegalState Failed to load ApplicationContext
[ERROR]   FaqResourceTest.test » IllegalState Failed to load ApplicationContext
[ERROR]   ImprintResourceTest.test » IllegalState Failed to load ApplicationContext
[ERROR]   IndexResourceTest.test » IllegalState Failed to load ApplicationContext
[ERROR]   LoginResourceTest.test » IllegalState Failed to load ApplicationContext
[ERROR]   MessageResourceTest.test » IllegalState Failed to load ApplicationContext
[ERROR]   NotificationResourceTest.test » IllegalState Failed to load ApplicationContext
[ERROR]   PasswordResourceTest.test » IllegalState Failed to load ApplicationContext
[ERROR]   PrivacyResourceTest.test » IllegalState Failed to load ApplicationContext
[ERROR]   ProfileResourceTest.test » IllegalState Failed to load ApplicationContext
[ERROR]   RegisterResourceTest.test » IllegalState Failed to load ApplicationContext
[ERROR]   SearchResourceTest.test » IllegalState Failed to load ApplicationContext
[ERROR]   TermsConditionsResourceTest.test » IllegalState Failed to load ApplicationCont...
[ERROR]   TosResourceTest.test » IllegalState Failed to load ApplicationContext
[ERROR]   UserProfileResourceTest.test » IllegalState Failed to load ApplicationContext
[ERROR]   TextEncryptorConverterTest.decrypt » IllegalState Failed to load ApplicationCo...
[ERROR]   TextEncryptorConverterTest.encrypt » IllegalState Failed to load ApplicationCo...
[ERROR]   AdminServiceTest.test » IllegalState Failed to load ApplicationContext
[ERROR]   CaptchaServiceTest.test » IllegalState Failed to load ApplicationContext
[ERROR]   DonateServiceTest.test » IllegalState Failed to load ApplicationContext
[ERROR]   DonateServiceTest.testWithRealDataKofi » IllegalState Failed to load Applicati...
[ERROR]   MailServiceTest.test » IllegalState Failed to load ApplicationContext
[ERROR]   NotificationServiceTest.test » IllegalState Failed to load ApplicationContext
[ERROR]   PasswordServiceTest.test » IllegalState Failed to load ApplicationContext
[ERROR]   RegisterServiceTest.test » IllegalState Failed to load ApplicationContext
[ERROR]   ScheduleServiceTest.test » IllegalState Failed to load ApplicationContext
[ERROR]   SearchAndMessageServiceTest.test » IllegalState Failed to load ApplicationCont...
[ERROR]   UserServiceTest.test » IllegalState Failed to load ApplicationContext
[ERROR]   UserServiceTest.testGetInterestAutocomplete » IllegalState Failed to load Appl...
[INFO] 
[ERROR] Tests run: 37, Failures: 0, Errors: 33, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:51 min
[INFO] Finished at: 2022-12-23T14:22:24+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project alovoa: There are test failures.
[ERROR] 
[ERROR] Please refer to C:\Users\jayje\git\alovoa\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project alovoa: There are test failures.

Please refer to C:\Users\jayje\git\alovoa\target\surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions(MojoExecutor.java:355)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:200)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.

Please refer to C:\Users\jayje\git\alovoa\target\surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
	at org.apache.maven.plugin.surefire.SurefireHelper.throwException(SurefireHelper.java:289)
	at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution(SurefireHelper.java:161)
	at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary(SurefirePlugin.java:364)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1041)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	... 24 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by Nonononoki** [comment]
You need a local database for the tests.
For reference, you can check out how the Github CI/CD does it: https://github.com/Alovoa/alovoa/blob/master/.github/workflows/maven.yml
