### ISSUE TITLE
[BUG] com.nonononoki.alovoa.entity.User.getDates is null exception

### ISSUE THREAD

**Issue by peterzen** [Alovoa/alovoa#305]
**Describe the bug**
When logged in using the admin user, the below exception is thrown:

```
2023-09-02 11:09:15 ERROR c.n.a.component.ExceptionHandler - java.lang.NullPointerException: Cannot invoke "com.nonononoki.alovoa.entity.user.UserDates.getNotificationDate()" because the return value of "com.nonononoki.alovoa.entity.User.getDates()" is null
	at com.nonononoki.alovoa.service.UserService.hasNewAlert(UserService.java:805)
	at com.nonononoki.alovoa.service.UserService.hasNewAlert(UserService.java:796)
	at com.nonononoki.alovoa.rest.UserController.newAlert(UserController.java:240)
	at jdk.internal.reflect.GeneratedMethodAccessor74.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
```

**To Reproduce**
1. Log in with admin user/key
2. Observer log

**Expected behavior**
No exception thrown

**Desktop (please complete the following information):**
- Any device

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Nonononoki** [comment]
Closing issue because of inactivity. Feel free to re-submit a bug ticket if the issue persist.
