### ISSUE TITLE
[BUG] Cannot edit profile

### ISSUE THREAD

**Issue by gnaomo** [Alovoa/alovoa#358]
**Describe the bug**
On my Android whenever I click edit profile on the web a blank page appears, if I do it on the app it crashes immediately with no message. Even on other devices such as my computer the behavior is the same.

**To Reproduce**
1. Go to 'Profile'
2. Click on 'Edit Profile'

**Screenshots**
![Screenshot_2024-02-17-10-01-54-72_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Alovoa/alovoa/assets/38522864/5ba31fcd-c377-4f7e-a308-3adc6fcc6e80)

**Additional context**
With another account it works.

**Comment by gnaomo** [comment]
Using LogFox I catched the error

```
FATAL EXCEPTION: mqt_native_modules
Process: com.alovoa.expo, PID: 13105
com.facebook.react.common.JavascriptException: TypeError: Cannot read property 'length' of null
This error is located at:
    in ProfileSettings
    in StaticContainer
    in EnsureSingleNavigator
    in SceneView
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in CardSheet
    in RCTView
    in Unknown
    in Unknown
    in PanGestureHandler
    in PanGestureHandler
    in RCTView
    in Unknown
    in Unknown
    in RCTView
    in Unknown
    in Card
    in CardContainer
    in RNSScreen
    in Unknown
    in Suspender
    in Suspense
    in Freeze
    in DelayedFreeze
    in InnerScreen
    in Screen
    in MaybeScreen
    in RNSScreenContainer
    in ScreenContainer
    in MaybeScreenContainer
    in RCTView
    in Unknown
    in Background
    in CardStack
    in RCTView
    in Unknown
    in SafeAreaProviderCompat
    in RNGestureHandlerRootView
    in GestureHandlerRootView
    in StackView
    in PreventRemoveProvider
    in NavigationContent
    in Unknown
    in StackNavigator
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner
    in ThemeProvider
    in RCTView
    in Unknown
    in Portal.Host
    in RNCSafeAreaProvider
    in SafeAreaProvider
    in SafeAreaProviderCompat
    in PaperProvider
    in App
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in AppContainer, js engine: hermes, stack:
ProfileSettings@1:2347272
renderWithHooks@1:343877
updateFunctionComponent@1:350140
beginWork$1@1:384227
performUnitOfWork@1:371211
workLoopSync@1:371114
renderRootSync@1:370998
performSyncWorkOnRoot@1:368486
flushSyncCallbacks@1:333575
batchedUpdatesImpl@1:384933
batchedUpdates@1:326458
_receiveRootNodeIDEvent@1:326731
receiveTouches@1:379789
__callFunction@1:83507
anonymous@1:82000
__guard@1:82940
callFunctionReturnFlushedQueue@1:81958
	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:65)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
	at com.facebook.jni.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by Nonononoki** [comment]
Wrong repo, please post your bug report here: https://github.com/Alovoa/alovoa-expo/issues
Also, the web app isn't working properly on Android browsers, please use the native app.
